services:
  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      # - MYSQL_DATABASE=auth_db
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3316:3306"
    networks:
      - app-network

  redis:
    image: redis:7.0
    ports:
      - "6389:6379"
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3.12-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5972:5672"
      - "19672:15672"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
