CREATE DATABASE IF NOT EXISTS auth_db;
CREATE DATABASE IF NOT EXISTS product_db;

GRANT ALL PRIVILEGES ON auth_db.* TO 'user'@'%' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON product_db.* TO 'user'@'%' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;
